spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_solchell
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # todo nginx와 같은 리버스 프록시 서버에도 크기 설정을 해줘야 함.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

firebase:
  credential:
    resource-path: firebase.json